### ISSUE TITLE
Discord webhook with changelog plugin.

### ISSUE THREAD

**Issue by KingsRequin** [AzuriomCommunity/Plugin-Changelog#10] opened 2023-04-21 19:31 UTC
Everything is in the title, it would be nice to be able to send the changelog on his discord.

**Comment by MrMicky-FR** [comment] 2023-05-02 04:13
Duplicate of #2

**Closed by MrMicky-FR** 2023-05-02 04:13 UTC
Labels: duplicate

**Comment by MrMicky-FR** [comment] 2024-06-19 11:14
Added in version 1.2.2 🚀
